steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA']
  # Deploy container image to Compute Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'compute'
    - 'instances'
    - 'create'
    - 'instance-with-cloud-build'
    - '--image-project'
    - 'my-cluster-project-407509'
    - '--container-image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA'
    - '--machine-type'
    - 'e2-medium'
    # - '--REGION'
    # - 'asia-south1'
    - '--zone'
    - 'asia-south1-c'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA'