steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA']
  # Deploy container image to Compute Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'compute'
    - 'instances'
    - 'deploy'
    - 'instance-with-cloud-build'
    - '--image'
    - 'gcr.io/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA'
    - '--REGION'
    - 'asia-south1'
    - '--ZONE'
    - 'asia-south1-c'
images:
  - 'gcr.io/$PROJECT_ID/instance-with-cloud-build:$COMMIT_SHA'